language: bash
os: linux
dist: bionic
sudo: enabled
env:
  global:
    - LC_ALL: C.UTF-8
    - LANG: C.UTF-8
    - SNAPCRAFT_BUILD_ENVIRONMENT: 'lxd'
    - SNAPCRAFT_BUILD_INFO: 1

addons:
  snaps:
   - name: snapcraft
     channel: stable
     confinement: classic
   - name: lxd
     channel: stable

install:
  - sudo usermod --append --groups lxd $USER
  - sudo /snap/bin/lxd.migrate -yes
  - sudo /snap/bin/lxd waitready
  - sudo /snap/bin/lxd init --auto
  - mkdir -p "$TRAVIS_BUILD_DIR/snaps-cache"
script:
  - sg lxd -c snapcraft
after_failure:
  - sudo journalctl -u snapd
